GET http://localhost:4000/api/v1/jobs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF4ZSIsIm5hbWUiOiJNb2d1bCBLaGFuIiwiaWQiOiI2MDc0ZGJmNGQ4ZDM5MzFiY2U5MzE1ZGYiLCJpYXQiOjE2MTg2ODg3NzksImV4cCI6MTYxODY5MjM3OX0.DAy__psHTTVvws7RgVil4Dnb1g60z3L67dceZ3M7lu4