POST http://localhost:4000/api/v1/jobs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxlc2hyYWMiLCJuYW1lIjoiTGVzaHJhYyIsImlkIjoiNjA3YTIzOWY4ZjIyY2QxYWJhNTRkYjM4IiwiaWF0IjoxNjE4NjE3MjYwLCJleHAiOjE2MTg2MjA4NjB9.GDPusWHg57jP467FKQSTLr-Cn3mBi-zcKuM-0T33Qmc
Content-Type: application/json

{
    "title": "Owner",
    "city": "Toronto",
    "company": "Dota Corporation",
    "link": "https://www.dota.ca",
    "notes": "N/A",
    "status": 1
}